### ISSUE TITLE
Data *Warehouse* For Democracy

### ISSUE THREAD

**Issue by adamhaney** [Data4Democracy/project-ideas#2]
# Motivation
There are TONS of publicly available datasets in various formats made available by local, state and federal agencies. BUT, there's quite a bit of labor involved in massaging their data into a usable format. In enterprise environments, it's common to have a "data warehouse" which enforces a common data schema that outside data is molded into.

It could be valuable to create a shared data warehouse resource (I have some hardware that I might be able to donate to this cause). We could then predigest/prejoin data that relates to various common areas (or other facts/dimensions that may not yet be obvious to me). This data could support the exploratory phase of data science work or help to model the impacts of various policies in an open source way.

## Example Data sources that could be pre-merged
  - Open Street Map
  - Census Tigerline Dataset
  - Housing Data From HUD (https://data.hud.gov/data_sets.html)

### Zipcode Fact
  - (Integer) zcta5 
  - (Polygon) boundaries

### Zipcode Year Dimension
  - (Varchar 255) Congressional Representative
  - (Varchar 255) Congressional Representative Political Party
  - (Varchar 255) Senate Representative
  ... Other Elected Official Information ...
  - (Integer) Public Housing Units
  - (Integer) Public Housing Facilities
  - (Decimal) Median Income
  ... Other summary statistics about the area's population ...

### Postgres (https://www.postgresql.org/)
I've used PostgreSQL for warehouse projects before with great success, it's open source, supports geospatial querying which could be useful for querying regional data and supports foreign data wrappers and database followers which could be useful for mirroring if the dataset were to grow in size or usage to the point that additional resources were needed.

### Airflow (https://airflow.incubator.apache.org/)
Airflow is an open source ETL tool created by Airbnb and now being Incubated by the Apache Foundation. We could use this tool to do fetching and transformation of the data before it was placed in the warehouse. I'm proposing that Postgres/Airflow be hosted somewhere and that then their configuration/code be available somewhere publicly (github?) so that adding data sources to the warehouse would be as simple as merging a pull request.

### DBT (https://dbt.readme.io/docs/overview)
DBT is a tool that makes it easy to use SQL to transform data in its raw format into "models" which are tables that are more useful for analysis. I believe this would make it easier to shape the data coming from various sources into a common fact/dimension table format that would facilitate easier analysis.

**Comment by bstarling** [comment]
This seems very much in line with what [data.world](https://data.world/about/) is trying to do. They are partners with the data 4 democracy org. @sharonbrener and others are very active in doing what they can to support the community. If you have interesting data sets you can load them to data.world and work on combining them with other publicly available datasets which may already be on the portal.

**Comment by jonloyens** [comment]
Hi @adamhaney - I believe that data.world supports most of what you're looking for.  If you want specific examples or would like to discuss an ETL architecture that could work, please let me or @bryonjacob know

**Comment by bnsmith3** [comment]
So, does that make this issue effectively closed?...
